# Generated by Django 3.1.4 on 2021-01-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=10)),
                ('disc', models.TextField(max_length=20)),
            ],
        ),
    ]
